env:
  - name: ENVIRONMENT
    value: production

hostName: bahn.expert
alternativeHostNames:
  - abfahrten.in
  - marudor.de

replicaCount: 5

disruption:
  maxUnavailable: 3

resources:
  requests:
    memory: '1Gi'
    cpu: '600m'
  limits:
    memory: '1Gi'
